const url = 'http://localhost:3060';
export default {
  register: `${url}/auth/register`,
  login: `${url}/auth/login`,
  logout: `${url}/auth/logout`,
  adminBasics: `${url}/admin/adminBasics`,
  addBasic: `${url}/admin/addBasic`,
  updateBasic: `${url}/admin/updateBasic`,
  adminBlogMeta: `${url}/admin/adminBlogMeta`,
  addBlogMeta: `${url}/admin/addBlogMeta`,
  updateBlogMeta: `${url}/admin/updateBlogMeta`,
  adminBlogs: `${url}/admin/adminBlogs`,
  addBlog: `${url}/admin/addBlog`,
  updateBlog: `${url}/admin/updateBlog`,
  blogMetaOptions: `${url}/admin/blogMetaOptions`,
  getBlog: `${url}/admin/getBlog/`,
  adminVideos: `${url}/admin/adminVideos`,
  addVideo: `${url}/admin/addVideo`,
  updateVideo: `${url}/admin/updateVideo`,
  adminMetas: `${url}/admin/adminMetas`,
  addMeta: `${url}/admin/addMeta`,
  updateMeta: `${url}/admin/updateMeta`,
  blogs: `${url}/blog`,
  singleBlog: `${url}/single/`,
  suggestBlogs: `${url}/suggestBlogs`,
  videos: `${url}/admin/videos/`,
  subjects: `${url}/admin/subjects/`,
  addComment: `${url}/admin/addComment`,
};
